version: '3.4'
services:
  node:
    image: node:14
    working_dir: /app
    # command: sh -c "npm i && npm run build && npm start"
    command: sh -c "yarn install && yarn run dev"
    volumes:
      - ./:/app
    ports:
      - 9000:9000
    env_file: .env
    environment:
      PORT: "9000"
